interface Achievement {
  id: string;
  name: string;
  description: string;
  showIcons: boolean;
  requiredCards?: Array<{
    cardKey: string;
    cardKeyBase?: string;
    variant?: string;
    isShiny?: boolean;
    minCount?: number;
  }>;
  collectionGoal?: {
    property: 'type' | 'rarity' | 'isShiny' | 'region';
    value?: string;
    targetCount: number;
  };
}

export const achievements: Achievement[] = [
  {
    id: 'starters',
    name: 'First Picks',
    description: 'Collect all First Parter Pokémon.',
    showIcons: true,
    requiredCards: [
      { cardKey: 'Bulbasaur-1' },
      { cardKey: 'Charmander-4' },
      { cardKey: 'Squirtle-7' },
      { cardKey: 'Chikorita-152' },      
      { cardKey: 'Cyndaquil-155' },      
      { cardKey: 'Totodile-158' },      
      { cardKey: 'Treecko-252' },      
      { cardKey: 'Torchic-255' },      
      { cardKey: 'Mudkip-258' },      
      { cardKey: 'Turtwig-387' },      
      { cardKey: 'Chimchar-390' },      
      { cardKey: 'Piplup-393' },      
      { cardKey: 'Snivy-495' },      
      { cardKey: 'Tepig-498' },      
      { cardKey: 'Oshawott-501' },      
      { cardKey: 'Chespin-650' },      
      { cardKey: 'Fennekin-653' },      
      { cardKey: 'Froakie-656' },      
      { cardKey: 'Rowlet-722' },      
      { cardKey: 'Litten-725' },      
      { cardKey: 'Popplio-728' },      
      { cardKey: 'Grookey-810' },      
      { cardKey: 'Scorbunny-813' },      
      { cardKey: 'Sobble-816' },      
      { cardKey: 'Sprigatito-906' },      
      { cardKey: 'Fuecoco-909' },      
      { cardKey: 'Quaxly-912' },      
    ],
  },
    {
    id: 'eevee',
    name: 'Veevee Volley',
    description: 'Collect Eevee and all of its Evolutions',
    showIcons: true,
    requiredCards: [
      { cardKey: 'Eevee-133' },
      { cardKey: 'Vaporeon-134' },
      { cardKey: 'Jolteon-135' },
      { cardKey: 'Flareon-136' },
      { cardKey: 'Espeon-196' },
      { cardKey: 'Umbreon-197' },
      { cardKey: 'Leafeon-470' },
      { cardKey: 'Glaceon-471' },
      { cardKey: 'Sylveon-700' },
      { cardKey: 'GMax Eevee-133', variant: 'GMax'}
    ],
  },
    {
    id: 'pika',
    name: 'Pika! Pika!',
    description: 'Collect Pokemon with Electric Cheeks',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Pichu-172' },
  { cardKey: 'Pikachu-25' },
  { cardKey: 'Raichu-26' },
  { cardKey: 'Raichu (Alola)-26', variant: 'Alola' },
  { cardKey: 'Plusle-311' },
  { cardKey: 'Minun-312' },
  { cardKey: 'Pachirisu-417' },
  { cardKey: 'Emolga-587' },
  { cardKey: 'Dedenne-702' },
  { cardKey: 'Togedemaru-777' },
  { cardKey: 'Mimikyu-778' },
  { cardKey: 'Morpeko-877' },
  { cardKey: 'Pawmi-921' },
  { cardKey: 'Pawmo-922' },
  { cardKey: 'Pawmot-923' },
  { cardKey: 'GMax Pikachu-25', variant: 'GMax' },
]
  },
    {
    id: 'meowth',
    name: "Meowth that's Right",
    description: 'Collect All Meowth Variants and Evolutions',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Meowth-52' },
  { cardKey: 'Persian-53' },
  { cardKey: 'Meowth (Alola)-52', variant: 'Alola' },
  { cardKey: 'Persian (Alola)-53', variant: 'Alola' },
  { cardKey: 'Meowth (Galar)-52', variant: 'Galar' },
  { cardKey: 'Perrserker-863' },
  { cardKey: 'GMax Meowth-52', variant: 'GMax' },
]
  },
    {
    id: 'Ash',
    name: 'I Choose You',
    description: "Collect all of Ash's Pokemon",
    showIcons: true,
    requiredCards: [
  { cardKey: 'Pikachu-25' },
  { cardKey: 'Butterfree-12' },
  { cardKey: 'Pidgeot-18' },
  { cardKey: 'Bulbasaur-1' },
  { cardKey: 'Charizard-6' },
  { cardKey: 'Squirtle-7' },
  { cardKey: 'Primeape-57' },
  { cardKey: 'Kingler-99' },
  { cardKey: 'Muk-89' },
  { cardKey: 'Tauros-128' },
  { cardKey: 'Snorlax-143' },
  { cardKey: 'Lapras-131' },
  { cardKey: 'Heracross-214' },
  { cardKey: 'Bayleef-153' },
  { cardKey: 'Quilava-156' },
  { cardKey: 'Totodile-158' },
  { cardKey: 'Noctowl-164', isShiny: true },
  { cardKey: 'Donphan-232' },
  { cardKey: 'Larvitar-246' },
  { cardKey: 'Swellow-277' },
  { cardKey: 'Sceptile-254' },
  { cardKey: 'Corphish-341' },
  { cardKey: 'Torkoal-324' },
  { cardKey: 'Glalie-362' },
  { cardKey: 'Staraptor-398' },
  { cardKey: 'Torterra-389' },
  { cardKey: 'Infernape-392' },
  { cardKey: 'Buizel-418' },
  { cardKey: 'Gliscor-472' },
  { cardKey: 'Gible-443' },
  { cardKey: 'Unfezant♀-521', variant: 'female' },
  { cardKey: 'Oshawott-501' },
  { cardKey: 'Pignite-499' },
  { cardKey: 'Snivy-495' },
  { cardKey: 'Scraggy-559' },
  { cardKey: 'Leavanny-542' },
  { cardKey: 'Palpitoad-536' },
  { cardKey: 'Boldore-525' },
  { cardKey: 'Krookodile-553' },
  { cardKey: 'Greninja-658' },
  { cardKey: 'Talonflame-663' },
  { cardKey: 'Hawlucha-701' },
  { cardKey: 'Goodra-706' },
  { cardKey: 'Noivern-715' },
  { cardKey: 'Rowlet-722' },
  { cardKey: 'Lycanroc (Dusk)-745', variant: "Dusk" },
  { cardKey: 'Incineroar-727' },
  { cardKey: 'Melmetal-809' },
  { cardKey: 'Naganadel-804' },
  { cardKey: 'Solgaleo-791' },
  { cardKey: 'Dragonite-149' },
  { cardKey: 'Gengar-94' },
  { cardKey: 'Lucario-448' },
  { cardKey: "Sirfetch'd-865" },
  { cardKey: 'Dracovish-882' },
]
  },
    {
    id: 'baby',
    name: 'Daycare Attendant',
    description: 'Collect every Baby Pokemon',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Pichu-172' },
  { cardKey: 'Cleffa-173' },
  { cardKey: 'Igglybuff-174' },
  { cardKey: 'Togepi-175' },
  { cardKey: 'Tyrogue-236' },
  { cardKey: 'Smoochum-238' },
  { cardKey: 'Elekid-239' },
  { cardKey: 'Magby-240' },
  { cardKey: 'Azurill-298' },
  { cardKey: 'Wynaut-360' },
  { cardKey: 'Budew-406' },
  { cardKey: 'Chingling-433' },
  { cardKey: 'Bonsly-438' },
  { cardKey: 'Mime Jr.-439' },
  { cardKey: 'Happiny-440' },
  { cardKey: 'Munchlax-446' },
  { cardKey: 'Riolu-447' },
  { cardKey: 'Mantyke-458' },
  { cardKey: 'Toxel-848' },
],
  },
    {
    id: 'pseudo',
    name: '600 BST Club',
    description: 'Collect every Pokemon with 600 BST',
    showIcons: true,
requiredCards: [
  { cardKey: 'Dragonite-149' },
  { cardKey: 'Tyranitar-248' },
  { cardKey: 'Salamence-373' },
  { cardKey: 'Metagross-376' },
  { cardKey: 'Garchomp-445' },
  { cardKey: 'Hydreigon-635' },
  { cardKey: 'Goodra-706' },
  { cardKey: 'Kommo-o-784' },
  { cardKey: 'Dragapult-887' },
  { cardKey: 'Goodra (Hisui)-706', variant: 'Hisui' },
  { cardKey: 'Baxcalibur-998' },
  { cardKey: 'Archaludon-1018' },
]

  },
    {
    id: 'trade',
    name: 'I Hate Everstones',
    description: 'Collect every Trade Evolution Pokemon',
    showIcons: true,
  requiredCards: [
  { cardKey: 'Alakazam-65' },
  { cardKey: 'Machamp-68' },
  { cardKey: 'Golem-76' },
  { cardKey: 'Gengar-94' },
  { cardKey: 'Politoed-186' },
  { cardKey: 'Slowking-199' },
  { cardKey: 'Steelix-208' },
  { cardKey: 'Kingdra-230' },
  { cardKey: 'Scizor-212' },
  { cardKey: 'Porygon2-233' },
  { cardKey: 'Porygon-Z-474' },
  { cardKey: 'Milotic-350' },
  { cardKey: 'Huntail-367' },
  { cardKey: 'Gorebyss-368' },
  { cardKey: 'Rhyperior-464' },
  { cardKey: 'Electivire-466' },
  { cardKey: 'Magmortar-467' },
  { cardKey: 'Dusknoir-477' },
  { cardKey: 'Gigalith-526' },
  { cardKey: 'Conkeldurr-534' },
  { cardKey: 'Escavalier-589' },
  { cardKey: 'Accelgor-617' },
  { cardKey: 'Aromatisse-683' },
  { cardKey: 'Slurpuff-685' },
  { cardKey: 'Trevenant-709' },
  { cardKey: 'Gourgeist-711' },
  // { cardKey: 'Golem (Alola)-76', variant: 'Alola' },
]

  },
    {
    id: 'legendary-birds',
    name: 'Uno, Dos, Tres',
    description: 'Collect all forms of the Legendary Birds',
    showIcons: true,
    requiredCards: [
      { cardKey: 'Articuno-144' },
      { cardKey: 'Zapdos-145' },
      { cardKey: 'Moltres-146' },
      { cardKey: 'Articuno (Galar)-144', variant: 'Galar' },
      { cardKey: 'Zapdos (Galar)-145', variant: 'Galar' },
      { cardKey: 'Moltres (Galar)-146', variant: 'Galar' },
    ],
  },
      {
    id: 'safari',
    name: 'Safari Hunt',
    description: 'Collect all Pokemon from the Safari Zone',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Nidoran♀-29' },
  { cardKey: 'Nidorina-30' },
  { cardKey: 'Nidoran♂-32' },
  { cardKey: 'Nidorino-33' },
  { cardKey: 'Paras-46' },
  { cardKey: 'Parasect-47' },
  { cardKey: 'Venonat-48' },
  { cardKey: 'Venomoth-49' },
  { cardKey: 'Exeggcute-102' },
  { cardKey: 'Rhyhorn-111' },
  { cardKey: 'Chansey-113' },
  { cardKey: 'Tangela-114' },
  { cardKey: 'Scyther-123' },
  { cardKey: 'Pinsir-127' },
  { cardKey: 'Magikarp-129' },

  { cardKey: 'Poliwag-60' },
  { cardKey: 'Goldeen-118' },
  { cardKey: 'Psyduck-54' },
  { cardKey: 'Slowpoke-79' },
  { cardKey: 'Krabby-98' },

  { cardKey: 'Dratini-147' },
  { cardKey: 'Dragonair-148' },

  { cardKey: 'Doduo-84' },
  { cardKey: 'Cubone-104' },
  { cardKey: 'Marowak-105' },
  { cardKey: 'Kangaskhan-115' },
  { cardKey: 'Tauros-128' },
]
  },
//   {
//   id: 'gholdengo',
//   name: 'Good as Gold',
//   description: 'Collect 99 Gimmighoul (any form) and a Gholdengo.',
//   showIcons: false,
//   requiredCards: [
//     {
//       cardKey: 'Gimmighoul-999',
//       cardKeyBase: 'Gimmighoul-999',
//       minCount: 99,
//     },
//     {
//       cardKey: 'Gimmighoul-999-Roaming',
//       cardKeyBase: 'Gimmighoul-999',
//       minCount: 0,
//       variant: 'Roaming',
//     },
//     { cardKey: 'Gholdengo-1000' },
//   ],
  
// },
  {
    id: 'unown',
    name: 'Unown',
    description: 'Collect Every Unown Form',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Unown (A)-201', variant: 'a'},
  { cardKey: 'Unown (B)-201', variant: 'b' },
  { cardKey: 'Unown (C)-201', variant: 'c' },
  { cardKey: 'Unown (D)-201', variant: 'd' },
  { cardKey: 'Unown (E)-201', variant: 'e' },
  { cardKey: 'Unown (F)-201', variant: 'f' },
  { cardKey: 'Unown (G)-201', variant: 'g' },
  { cardKey: 'Unown (H)-201', variant: 'h' },
  { cardKey: 'Unown (I)-201', variant: 'i' },
  { cardKey: 'Unown (J)-201', variant: 'j' },
  { cardKey: 'Unown (K)-201', variant: 'k' },
  { cardKey: 'Unown (L)-201', variant: 'l' },
  { cardKey: 'Unown (M)-201', variant: 'm' },
  { cardKey: 'Unown (N)-201', variant: 'n' },
  { cardKey: 'Unown (O)-201', variant: 'o' },
  { cardKey: 'Unown (P)-201', variant: 'p' },
  { cardKey: 'Unown (Q)-201', variant: 'q' },
  { cardKey: 'Unown (R)-201', variant: 'r' },
  { cardKey: 'Unown (S)-201', variant: 's' },
  { cardKey: 'Unown (T)-201', variant: 't' },
  { cardKey: 'Unown (U)-201', variant: 'u' },
  { cardKey: 'Unown (V)-201', variant: 'v' },
  { cardKey: 'Unown (W)-201', variant: 'w' },
  { cardKey: 'Unown (X)-201', variant: 'x' },
  { cardKey: 'Unown (Y)-201', variant: 'y' },
  { cardKey: 'Unown (Z)-201', variant: 'z' },
  { cardKey: 'Unown (!)-201', variant: 'exclamation' },
  { cardKey: 'Unown (?)-201', variant: 'question' },
]

  },
  {
    id: 'fossil',
    name: 'Restore & Renew',
    description: 'Collect Every Fossil Pokemon',
    showIcons: true,
requiredCards: [
  { cardKey: 'Omanyte-138' },
  { cardKey: 'Omastar-139' },
  { cardKey: 'Kabuto-140' },
  { cardKey: 'Kabutops-141' },
  { cardKey: 'Aerodactyl-142' },
  { cardKey: 'Mega Aerodactyl-142', variant: 'Mega' },
  { cardKey: 'Lileep-345' },
  { cardKey: 'Cradily-346' },
  { cardKey: 'Anorith-347' },
  { cardKey: 'Armaldo-348' },
  { cardKey: 'Cranidos-408' },
  { cardKey: 'Rampardos-409' },
  { cardKey: 'Shieldon-410' },
  { cardKey: 'Bastiodon-411' },
  { cardKey: 'Tirtouga-564' },
  { cardKey: 'Carracosta-565' },
  { cardKey: 'Archen-566' },
  { cardKey: 'Archeops-567' },
  { cardKey: 'Tyrunt-696' },
  { cardKey: 'Tyrantrum-697' },
  { cardKey: 'Amaura-698' },
  { cardKey: 'Aurorus-699' },
  { cardKey: 'Dracozolt-880' },
  { cardKey: 'Arctozolt-881' },
  { cardKey: 'Dracovish-882' },
  { cardKey: 'Arctovish-883' },
]  },
  {
    id: 'amity',
    name: 'Cute Pokemon',
    description: 'Collect Pokemon that can stroll in Amity Square',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Pikachu-25' },
  { cardKey: 'Clefairy-35' },
  { cardKey: 'Jigglypuff-39' },
  { cardKey: 'Psyduck-54' },
  { cardKey: 'Eevee-133' },
  { cardKey: 'Vaporeon-134' },
  { cardKey: 'Jolteon-135' },
  { cardKey: 'Flareon-136' },
  { cardKey: 'Espeon-196' },
  { cardKey: 'Umbreon-197' },
  { cardKey: 'Torchic-255' },
  { cardKey: 'Shroomish-285' },
  { cardKey: 'Skitty-300' },
  { cardKey: 'Turtwig-387' },
  { cardKey: 'Grotle-388' },
  { cardKey: 'Torterra-389' },
  { cardKey: 'Chimchar-390' },
  { cardKey: 'Monferno-391' },
  { cardKey: 'Infernape-392' },
  { cardKey: 'Piplup-393' },
  { cardKey: 'Prinplup-394' },
  { cardKey: 'Empoleon-395' },
  { cardKey: 'Pachirisu-417' },
  { cardKey: 'Drifloon-425' },
  { cardKey: 'Buneary-427' },
  { cardKey: 'Happiny-440' },
  { cardKey: 'Leafeon-470' },
  { cardKey: 'Glaceon-471' },
]

  },
  {
    id: 'regi',
    name: 'ÜN ÜN ÜN',
    description: 'Collect Regigigas and the Legendary Titans',
    showIcons: true,
    requiredCards: [
      { cardKey: 'Regirock-377' },
      { cardKey: 'Regice-378' },
      { cardKey: 'Registeel-379' },
      { cardKey: 'Regigigas-486' },
      { cardKey: 'Regieleki-894' },
      { cardKey: 'Regidrago-895' },
    ],
  },
    {
    id: 'flower',
    name: 'Gorgeous Flower Garden',
    description: 'Collect all forms of the Florges Line',
    showIcons: true,
requiredCards: [
  { cardKey: 'Flabébé (Red)-669' },
  { cardKey: 'Floette (Red)-670' },
  { cardKey: 'Florges (Red)-671' },
  { cardKey: 'Flabébé (Orange)-669', variant: 'orange' },
  { cardKey: 'Floette (Orange)-670', variant: 'orange' },
  { cardKey: 'Florges (Orange)-671', variant: 'orange' },
  { cardKey: 'Flabébé (Yellow)-669', variant: 'yellow' },
  { cardKey: 'Floette (Yellow)-670', variant: 'yellow' },
  { cardKey: 'Florges (Yellow)-671', variant: 'yellow' },
  { cardKey: 'Flabébé (Blue)-669', variant: 'blue' },
  { cardKey: 'Floette (Blue)-670', variant: 'blue' },
  { cardKey: 'Florges (Blue)-671', variant: 'blue' },
  { cardKey: 'Flabébé (White)-669', variant: 'white' },
  { cardKey: 'Floette (White)-670', variant: 'white' },
  { cardKey: 'Florges (White)-671', variant: 'white' },
  { cardKey: 'Floette (Eternal Flower)-670', variant: 'az' },
],
  },
    {
    id: 'vivillon',
    name: 'Pattern Collector',
    description: 'Collect all Vivillon Patterns',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Vivillon (Archipelago)-666', variant: 'archipelago' },
  { cardKey: 'Vivillon (Continental)-666', variant: 'continental' },
  { cardKey: 'Vivillon (Elegant)-666', variant: 'elegant' },
  { cardKey: 'Vivillon (Garden)-666', variant: 'garden' },
  { cardKey: 'Vivillon (High Plains)-666', variant: 'highplains' },
  { cardKey: 'Vivillon (Icy Snow)-666', variant: 'icysnow' },
  { cardKey: 'Vivillon (Jungle)-666', variant: 'jungle' },
  { cardKey: 'Vivillon (Marine)-666', variant: 'marine' },
  { cardKey: 'Vivillon (Modern)-666', variant: 'modern' },
  { cardKey: 'Vivillon (Monsoon)-666', variant: 'monsoon' },
  { cardKey: 'Vivillon (Ocean)-666', variant: 'ocean' },
  { cardKey: 'Vivillon (Polar)-666', variant: 'polar' },
  { cardKey: 'Vivillon (River)-666', variant: 'river' },
  { cardKey: 'Vivillon (Sandstorm)-666', variant: 'sandstorm' },
  { cardKey: 'Vivillon (Savanna)-666', variant: 'savanna' },
  { cardKey: 'Vivillon (Sun)-666', variant: 'sun' },
  { cardKey: 'Vivillon (Tundra)-666', variant: 'tundra' },
  { cardKey: 'Vivillon (Fancy)-666', variant: 'fancy' },
  { cardKey: 'Vivillon (Pokeball)-666', variant: 'pokeball' },
  { cardKey: 'Vivillon (Meadow)-666', variant: 'meadow' },
]

  },
  {
    id: 'tao',
    name: 'Truth/Ideals',
    description: 'Collect Reshiram, Zekrom, and Kyurem',
    showIcons: true,
    requiredCards: [
      { cardKey: 'Reshiram-643' },
      { cardKey: 'Kyurem (White)-646', variant: 'White' },
      { cardKey: 'Kyurem-646' },
      { cardKey: 'Kyurem (Black)-646', variant: 'Black' },
      { cardKey: 'Zekrom-644' },
    ],
  },
  {
    id: 'nature',
    name: 'Incarnate Forces',
    description: 'Collect the Forces of Nature',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Tornadus-641' },
  { cardKey: 'Tornadus (Therian)-641', variant: 'Therian' },
  { cardKey: 'Thundurus-642' },
  { cardKey: 'Thundurus (Therian)-642', variant: 'Therian' },
  { cardKey: 'Landorus-645' },
  { cardKey: 'Landorus (Therian)-645', variant: 'Therian' },
  { cardKey: 'Enamorus-905' },
  { cardKey: 'Enamorus (Therian)-905', variant: 'Therian' },
]
  },
  {
    id: 'totem',
    name: 'Totem Challenge',
    description: 'Collect the Totem Pokemon',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Gumshoos-735' },
  { cardKey: 'Raticate (Alola)-20', variant: 'Alola' },
  { cardKey: 'Wishiwashi (School)-746', variant: 'School' },
  { cardKey: 'Araquanid-752' },
  { cardKey: 'Salazzle-758' },
  { cardKey: 'Marowak (Alola)-105', variant: 'Alola' },
  { cardKey: 'Lurantis-754' },
  { cardKey: 'Vikavolt-738' },
  { cardKey: 'Togedemaru-777' },
  { cardKey: 'Mimikyu-778' },
  { cardKey: 'Kommo-o-784' },
  { cardKey: 'Ribombee-743' },
]
  },
  {
    id: 'myth',
    name: 'Myths of Hisui',
    description: 'Collect the Totem Pokemon',
    showIcons: true,
    requiredCards: [
    { cardKey: 'Wyrdeer-899' },
    { cardKey: 'Kleavor-900' },
    { cardKey: 'Lilligant (Hisui)-549', variant: 'Hisui' },
    { cardKey: 'Ursaluna-901' },
    { cardKey: 'Basculegion♂-902' },
    { cardKey: 'Arcanine (Hisui)-59', variant: 'Hisui' },
    { cardKey: 'Electrode (Hisui)-101', variant: 'Hisui' },
    { cardKey: 'Sneasler-903' },
    { cardKey: 'Braviary (Hisui)-628', variant: 'Hisui' },
    { cardKey: 'Avalugg (Hisui)-713', variant: 'Hisui' },
    { cardKey: 'Dialga (Origin)-483', variant: 'Origin' },
    { cardKey: 'Palkia (Origin)-484', variant: 'Origin' },
    { cardKey: 'Giratina (Origin)-487', variant: 'Origin' },
    { cardKey: 'Arceus-493'},
  ]
  },
      {
    id: 'silvally',
    name: 'RKS',
    description: 'Collect all Silvally Forms',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Type: Null-772' },
  { cardKey: 'Silvally-773' },
  { cardKey: 'Silvally (Fire)-773', variant: 'fire' },
  { cardKey: 'Silvally (Water)-773', variant: 'water' },
  { cardKey: 'Silvally (Electric)-773', variant: 'electric' },
  { cardKey: 'Silvally (Grass)-773', variant: 'grass' },
  { cardKey: 'Silvally (Ice)-773', variant: 'ice' },
  { cardKey: 'Silvally (Fighting)-773', variant: 'fighting' },
  { cardKey: 'Silvally (Poison)-773', variant: 'poison' },
  { cardKey: 'Silvally (Ground)-773', variant: 'ground' },
  { cardKey: 'Silvally (Flying)-773', variant: 'flying' },
  { cardKey: 'Silvally (Psychic)-773', variant: 'psychic' },
  { cardKey: 'Silvally (Bug)-773', variant: 'bug' },
  { cardKey: 'Silvally (Rock)-773', variant: 'rock' },
  { cardKey: 'Silvally (Ghost)-773', variant: 'ghost' },
  { cardKey: 'Silvally (Dragon)-773', variant: 'dragon' },
  { cardKey: 'Silvally (Dark)-773', variant: 'dark' },
  { cardKey: 'Silvally (Steel)-773', variant: 'steel' },
  { cardKey: 'Silvally (Fairy)-773', variant: 'fairy' },
]

  },
      {
    id: 'ultrabeast',
    name: 'UB: UNKNOWN',
    description: 'Collect all Ultra Beasts',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Nihilego-793' },
  { cardKey: 'Buzzwole-794' },
  { cardKey: 'Pheromosa-795' },
  { cardKey: 'Xurkitree-796' },
  { cardKey: 'Celesteela-797' },
  { cardKey: 'Kartana-798' },
  { cardKey: 'Guzzlord-799' },
  { cardKey: 'Poipole-803' },
  { cardKey: 'Naganadel-804' },
  { cardKey: 'Stakataka-805' },
  { cardKey: 'Blacephalon-806' },
]
  },
      {
    id: 'necrozma',
    name: 'Light that Burns the Sky',
    description: 'Collect Solgaleo, Lunala, Necrozma and all of its forms',
    showIcons: true,
    requiredCards: [
      { cardKey: 'Cosmog-789' },
      { cardKey: 'Cosmoem-790' },
      { cardKey: 'Solgaleo-791' },  
      { cardKey: 'Lunala-792' },  
      { cardKey: 'Necrozma-800' },  
      { cardKey: 'Dusk Mane Necrozma-800', variant: 'Dusk' },
      { cardKey: 'Dawn Wings Necrozma-800', variant: 'Dawn' },  
      { cardKey: 'Ultra Necrozma-800', variant: 'Ultra' },  
    ],
  },
    {
    id: 'apple',
    name: 'An Applin a Day',
    description: 'Collect Applin and all of its Evolutions and Forms',
    showIcons: true,
    requiredCards: [
      { cardKey: 'Applin-840' },
      { cardKey: 'Flapple-841' },
      { cardKey: 'GMax Flapple-841', variant: 'GMax' },
      { cardKey: 'Appletun-842' },  
      { cardKey: 'GMax Appletun-842', variant: 'GMax' },  
      { cardKey: 'Dipplin-1011' },  
      { cardKey: 'Hydrapple-1019' },  
    ],
  },
    {
    id: 'urshifu',
    name: 'Two Fists',
    description: 'Collect Kubfu and all of its Evolutions and Forms',
    showIcons: true,
    requiredCards: [
      { cardKey: 'Kubfu-891' },
      { cardKey: 'Urshifu (Single Strike)-892' },
      { cardKey: 'GMax Urshifu (Single Strike)-892', variant: 'GMaxSingle' },
      { cardKey: 'Urshifu (Rapid Strike)-892', variant: 'RapidStrike' },  
      { cardKey: 'GMax Urshifu (Rapid Strike)-892', variant: 'GMaxRapid' },  
    ],
  },
     {
    id: 'scarlet',
    name: 'Scarlet Book',
    description: 'Collect all Past Paradox Forms',
    showIcons: true,
    requiredCards: [
    { cardKey: 'Great Tusk-984' },
    { cardKey: 'Scream Tail-985' },
    { cardKey: 'Brute Bonnet-986' },
    { cardKey: 'Flutter Mane-987' },
    { cardKey: 'Slither Wing-988' },
    { cardKey: 'Sandy Shocks-989' },
    { cardKey: 'Roaring Moon-1005' },
    { cardKey: 'Walking Wake-1009' },
    { cardKey: 'Gouging Fire-1020' },
    { cardKey: 'Raging Bolt-1021' },
    { cardKey: 'Koraidon-1007' },
    ],
  },
     {
    id: 'violet',
    name: 'Violet Book',
    description: 'Collect all Future Paradox Forms',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Iron Treads-990' },
  { cardKey: 'Iron Bundle-991' },
  { cardKey: 'Iron Hands-992' },
  { cardKey: 'Iron Jugulis-993' },
  { cardKey: 'Iron Moth-994' },
  { cardKey: 'Iron Thorns-995' },
  { cardKey: 'Iron Valiant-1006' },
  { cardKey: 'Iron Leaves-1010' },
  { cardKey: 'Iron Boulder-1022' },
  { cardKey: 'Iron Crown-1023' },
  { cardKey: 'Miraidon-1008' },
],
  },

  {
    id: 'weather',
    name: 'Rain or Shine',
    description: 'Collect Pokemon who can set the Weather',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Vulpix-37' },
  { cardKey: 'Ninetales-38' },
  { cardKey: 'Torkoal-324' },
  { cardKey: 'Mega Charizard Y-6', variant: 'MegaY' },
  { cardKey: 'Groudon-383' },
  { cardKey: 'Primal Groudon-383', variant: 'Primal' },

  { cardKey: 'Politoed-186' },
  { cardKey: 'Pelipper-279' },
  { cardKey: 'Kyogre-382' },
  { cardKey: 'Primal Kyogre-382', variant: 'Primal' },

  { cardKey: 'Tyranitar-248' },
  { cardKey: 'Mega Tyranitar-248', variant: 'Mega' },
  { cardKey: 'Hippopotas-449' },
  { cardKey: 'Hippowdon-450' },
  { cardKey: 'Gigalith-526' },

  { cardKey: 'Snover-459' },
  { cardKey: 'Abomasnow-460' },
  { cardKey: 'Mega Abomasnow-460', variant: 'Mega' },
  { cardKey: 'Vanilluxe-584' },

  { cardKey: 'Vulpix (Alola)-37', variant: 'Alola' },
  { cardKey: 'Ninetales (Alola)-38', variant: 'Alola' },

  { cardKey: 'Amaura-698' },
  { cardKey: 'Aurorus-699' },
]

  },

//   {
//     id: 'terastal-master',
//     name: 'Terastal Master',
//     description: 'Collect all forms of Terapagos.',
//     showIcons: true,
//     requiredCards: [
//       { cardKey: 'Terapagos-1024' },
//       { cardKey: 'Terapagos (Terastal)-1024', variant: 'Terastal' },
//       { cardKey: 'Terapagos (Stellar)-1024', variant: 'Stellar' },
//     ],
//   },
  {
    id: 'mega',
    name: 'Go Beyond',
    description: 'Collect all Mega Forms',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Mega Venusaur-3', variant: 'Mega' },
  { cardKey: 'Mega Charizard X-6', variant: 'MegaX' },
  { cardKey: 'Mega Charizard Y-6', variant: 'MegaY' },
  { cardKey: 'Mega Blastoise-9', variant: 'Mega' },
  { cardKey: 'Mega Beedrill-15', variant: 'Mega' },
  { cardKey: 'Mega Pidgeot-18', variant: 'Mega' },
  { cardKey: 'Mega Alakazam-65', variant: 'Mega' },
  { cardKey: 'Mega Slowbro-80', variant: 'Mega' },
  { cardKey: 'Mega Gengar-94', variant: 'Mega' },
  { cardKey: 'Mega Kangaskhan-115', variant: 'Mega' },
  { cardKey: 'Mega Pinsir-127', variant: 'Mega' },
  { cardKey: 'Mega Gyarados-130', variant: 'Mega' },
  { cardKey: 'Mega Aerodactyl-142', variant: 'Mega' },
  { cardKey: 'Mega Mewtwo X-150', variant: 'MegaX' },
  { cardKey: 'Mega Mewtwo Y-150', variant: 'MegaY' },

  { cardKey: 'Mega Ampharos-181', variant: 'Mega' },
  { cardKey: 'Mega Scizor-212', variant: 'Mega' },
  { cardKey: 'Mega Heracross-214', variant: 'Mega' },
  { cardKey: 'Mega Houndoom-229', variant: 'Mega' },
  { cardKey: 'Mega Tyranitar-248', variant: 'Mega' },

  { cardKey: 'Mega Sceptile-254', variant: 'Mega' },
  { cardKey: 'Mega Blaziken-257', variant: 'Mega' },
  { cardKey: 'Mega Swampert-260', variant: 'Mega' },
  { cardKey: 'Mega Gardevoir-282', variant: 'Mega' },
  { cardKey: 'Mega Sableye-302', variant: 'Mega' },
  { cardKey: 'Mega Mawile-303', variant: 'Mega' },
  { cardKey: 'Mega Aggron-306', variant: 'Mega' },
  { cardKey: 'Mega Medicham-308', variant: 'Mega' },
  { cardKey: 'Mega Manectric-310', variant: 'Mega' },
  { cardKey: 'Mega Sharpedo-319', variant: 'Mega' },
  { cardKey: 'Mega Camerupt-323', variant: 'Mega' },
  { cardKey: 'Mega Altaria-334', variant: 'Mega' },
  { cardKey: 'Mega Banette-354', variant: 'Mega' },
  { cardKey: 'Mega Absol-359', variant: 'Mega' },
  { cardKey: 'Mega Glalie-362', variant: 'Mega' },
  { cardKey: 'Mega Salamence-373', variant: 'Mega' },
  { cardKey: 'Mega Metagross-376', variant: 'Mega' },
  { cardKey: 'Mega Latias-380', variant: 'Mega' },
  { cardKey: 'Mega Latios-381', variant: 'Mega' },
  { cardKey: 'Mega Rayquaza-384', variant: 'Mega' },
  { cardKey: 'Primal Kyogre-382', variant: 'Primal' },
  { cardKey: 'Primal Groudon-383', variant: 'Primal' },

  { cardKey: 'Mega Lopunny-428', variant: 'Mega' },
  { cardKey: 'Mega Garchomp-445', variant: 'Mega' },
  { cardKey: 'Mega Lucario-448', variant: 'Mega' },
  { cardKey: 'Mega Abomasnow-460', variant: 'Mega' },
  { cardKey: 'Mega Gallade-475', variant: 'Mega' },

  { cardKey: 'Mega Audino-531', variant: 'Mega' },
  { cardKey: 'Mega Diancie-719', variant: 'Mega' },
]
  },
  {
    id: 'gmax',
    name: 'To the MAX',
    description: 'Collect all GMax Forms',
    showIcons: true,
    requiredCards: [
  { cardKey: 'GMax Venusaur-3', variant: 'GMax' },
  { cardKey: 'GMax Charizard-6', variant: 'GMax' },
  { cardKey: 'GMax Blastoise-9', variant: 'GMax' },
  { cardKey: 'GMax Butterfree-12', variant: 'GMax' },
  { cardKey: 'GMax Pikachu-25', variant: 'GMax' },
  { cardKey: 'GMax Meowth-52', variant: 'GMax' },
  { cardKey: 'GMax Machamp-68', variant: 'GMax' },
  { cardKey: 'GMax Gengar-94', variant: 'GMax' },
  { cardKey: 'GMax Kingler-99', variant: 'GMax' },
  { cardKey: 'GMax Lapras-131', variant: 'GMax' },
  { cardKey: 'GMax Eevee-133', variant: 'GMax' },
  { cardKey: 'GMax Snorlax-143', variant: 'GMax' },
  { cardKey: 'GMax Garbodor-569', variant: 'GMax' },
  { cardKey: 'GMax Melmetal-809', variant: 'GMax' },
  { cardKey: 'GMax Rillaboom-812', variant: 'GMax' },
  { cardKey: 'GMax Cinderace-815', variant: 'GMax' },
  { cardKey: 'GMax Inteleon-818', variant: 'GMax' },
  { cardKey: 'GMax Corviknight-823', variant: 'GMax' },
  { cardKey: 'GMax Orbeetle-826', variant: 'GMax' },
  { cardKey: 'GMax Drednaw-834', variant: 'GMax' },
  { cardKey: 'GMax Coalossal-839', variant: 'GMax' },
  { cardKey: 'GMax Flapple-841', variant: 'GMax' },
  { cardKey: 'GMax Appletun-842', variant: 'GMax' },
  { cardKey: 'GMax Sandaconda-844', variant: 'GMax' },
  { cardKey: 'GMax Toxtricity-849', variant: 'GMax' },
  { cardKey: 'GMax Centiskorch-851', variant: 'GMax' },
  { cardKey: 'GMax Hatterene-858', variant: 'GMax' },
  { cardKey: 'GMax Grimmsnarl-861', variant: 'GMax' },
  { cardKey: 'GMax Alcremie-869', variant: 'GMax' },
  { cardKey: 'GMax Copperajah-879', variant: 'GMax' },
  { cardKey: 'GMax Duraludon-884', variant: 'GMax' },
  { cardKey: 'GMax Urshifu (Single Strike)-892', variant: 'GMaxSingle' },
  { cardKey: 'GMax Urshifu (Rapid Strike)-892', variant: 'GMaxRapid' },
  { cardKey: 'Eternamax Eternatus-890', variant: 'Eternamax' },
]

  },
  {
    id: 'break',
    name: 'BREAK',
    description: 'Collect all Pokemon with BREAK Cards',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Chesnaught-652' },
  { cardKey: 'Raichu-26' },
  { cardKey: 'Marowak-105' },
  { cardKey: 'Zoroark-571' },
  { cardKey: 'Florges (Red)-671' },
  { cardKey: 'Noivern-715' },
  { cardKey: 'Empoleon-395' },
  { cardKey: 'Beheeyem-606' },
  { cardKey: 'Noctowl-164' },
  { cardKey: 'Golduck-55' },
  { cardKey: 'Greninja-658' },
  { cardKey: 'Luxray-405' },
  { cardKey: 'Trevenant-709' },
  { cardKey: 'Raticate-20' },
  { cardKey: 'Delphox-655' },
  { cardKey: 'Omastar-139' },
  { cardKey: 'Carbink-703' },
  { cardKey: 'Bronzong-437' },
  { cardKey: 'Lugia-249' },
  { cardKey: 'Mandibuzz-630' },
  { cardKey: 'Wobbuffet-202' },
  { cardKey: 'Ho-Oh-250' },
  { cardKey: 'Crobat-169' },
  { cardKey: 'Yanmega-469' },
  { cardKey: 'Talonflame-663' },
  { cardKey: 'Pyroar♂-668' },
  { cardKey: 'Clawitzer-693' },
  { cardKey: 'Yveltal-717' },
  { cardKey: 'Xerneas-716', variant: 'active' },
  { cardKey: 'Hydreigon-635' },
  { cardKey: 'Arcanine-59' },
  { cardKey: 'Ninetales-38' },
  { cardKey: 'Starmie-121' },
  { cardKey: 'Nidoking-34' },
  { cardKey: 'Machamp-68' },
]

  },
  {
    id: 'illumina',
    name: 'Crystabloom',
    description: 'Collect the Illumina Phenomenon Pokemon',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Meganium (Lumina)-154', variant: 'lumina' },
{ cardKey: 'Milotic (Lumina)-350', variant: 'lumina' },
{ cardKey: 'Wishiwashi (Lumina)-746', variant: 'lumina' },  
{ cardKey: 'Volcarona (Lumina)-637', variant: 'lumina' },
{ cardKey: 'Steelix (Lumina)-208', variant: 'lumina' },
  { cardKey: 'Xerneas (Lumina)-716', variant: 'lumina' },
    ],
  },
  {
    id: 'dungeon',
    name: 'Heroes & Partners',
    description: 'Collect all Hero and Partner Pokemon',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Bulbasaur-1' },
  { cardKey: 'Charmander-4' },
  { cardKey: 'Squirtle-7' },
  { cardKey: 'Pikachu-25' },
  { cardKey: 'Meowth-52' },
  { cardKey: 'Psyduck-54' },
  { cardKey: 'Growlithe-58' },
  { cardKey: 'Machop-66' },
  { cardKey: 'Cubone-104' },
  { cardKey: 'Vulpix-37' },
  { cardKey: 'Eevee-133' },

  { cardKey: 'Chikorita-152' },
  { cardKey: 'Cyndaquil-155' },
  { cardKey: 'Totodile-158' },
  { cardKey: 'Pichu-172' },
  { cardKey: 'Togepi-175' },
  { cardKey: 'Mareep-179' },
  { cardKey: 'Wooper-194' },
  { cardKey: 'Teddiursa-216' },
  { cardKey: 'Elekid-239' },
  { cardKey: 'Phanpy-231' },

  { cardKey: 'Treecko-252' },
  { cardKey: 'Torchic-255' },
  { cardKey: 'Mudkip-258' },
  { cardKey: 'Skitty-300' },
  { cardKey: 'Azurill-298' },
  { cardKey: 'Wynaut-360' },

  { cardKey: 'Turtwig-387' },
  { cardKey: 'Chimchar-390' },
  { cardKey: 'Piplup-393' },
  { cardKey: 'Shinx-403' },
  { cardKey: 'Pachirisu-417' },
  { cardKey: 'Buneary-427' },
  { cardKey: 'Riolu-447' },
  { cardKey: 'Munchlax-446' },

  { cardKey: 'Snivy-495' },
  { cardKey: 'Tepig-498' },
  { cardKey: 'Oshawott-501' },
  { cardKey: 'Axew-610' },

  { cardKey: 'Chespin-650' },
  { cardKey: 'Fennekin-653' },
  { cardKey: 'Froakie-656' },
]
  },
  {
    id: 'heroes',
    name: 'The Six Heroes',
    description: 'Collect the Six Heroes from Pokemon: Horizons',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Rayquaza-384', isShiny: true },
  { cardKey: 'Arboliva-930' },
  { cardKey: 'Moltres (Galar)-146', variant: 'Galar' },
  { cardKey: 'Lapras-131' },
  { cardKey: 'Kleavor-900' },
  { cardKey: 'Gouging Fire-1020' },
    ],
  },
        {
    id: 'arceus',
    name: 'The Alpha Pokemon',
    description: 'Collect all Arceus Forms',
    showIcons: true,
    requiredCards: [
  { cardKey: 'Arceus-493' },
  { cardKey: 'Arceus (Fire)-493', variant: 'fire' },
  { cardKey: 'Arceus (Water)-493', variant: 'water' },
  { cardKey: 'Arceus (Electric)-493', variant: 'electric' },
  { cardKey: 'Arceus (Grass)-493', variant: 'grass' },
  { cardKey: 'Arceus (Ice)-493', variant: 'ice' },
  { cardKey: 'Arceus (Fighting)-493', variant: 'fighting' },
  { cardKey: 'Arceus (Poison)-493', variant: 'poison' },
  { cardKey: 'Arceus (Ground)-493', variant: 'ground' },
  { cardKey: 'Arceus (Flying)-493', variant: 'flying' },
  { cardKey: 'Arceus (Psychic)-493', variant: 'psychic' },
  { cardKey: 'Arceus (Bug)-493', variant: 'bug' },
  { cardKey: 'Arceus (Rock)-493', variant: 'rock' },
  { cardKey: 'Arceus (Ghost)-493', variant: 'ghost' },
  { cardKey: 'Arceus (Dragon)-493', variant: 'dragon' },
  { cardKey: 'Arceus (Dark)-493', variant: 'dark' },
  { cardKey: 'Arceus (Steel)-493', variant: 'steel' },
  { cardKey: 'Arceus (Fairy)-493', variant: 'fairy' },
  { cardKey: 'Arceus (???)-493', variant: 'unknown' },
]
  },
  {
    id: 'normal-collector',
    name: 'Schoolkid',
    description: 'Collect 100 Normal-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Normal',
      targetCount: 100,
    },
  },
  {
    id: 'fighting-collector',
    name: 'Black Belt',
    description: 'Collect 100 Fighting-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Fighting',
      targetCount: 100,
    },
  },
  {
    id: 'flying-collector',
    name: 'Bird Keeper',
    description: 'Collect 100 Flying-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Flying',
      targetCount: 100,
    },
  },
   {
    id: 'poison-collector',
    name: 'Punk',
    description: 'Collect 100 Poison-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Poison',
      targetCount: 100,
    },
  },
  {
    id: 'ground-collector',
    name: 'Ruin Maniac',
    description: 'Collect 100 Ground-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Ground',
      targetCount: 100,
    },
  },
  {
    id: 'rock-collector',
    name: 'Hiker',
    description: 'Collect 100 ROck-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Rock',
      targetCount: 100,
    },
  },
  {
    id: 'bug-collector',
    name: 'Bug Catcher',
    description: 'Collect 100 Bug-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Bug',
      targetCount: 100,
    },
  },
  {
    id: 'ghost-collector',
    name: 'Hex Maniac',
    description: 'Collect 100 Ghost-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Ghost',
      targetCount: 100,
    },
  },
  {
    id: 'steel-collector',
    name: 'Steel Worker',
    description: 'Collect 100 Steel-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Steel',
      targetCount: 100,
    },
  },
  {
    id: 'fire-collector',
    name: 'Kindler',
    description: 'Collect 100 Fire-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Fire',
      targetCount: 100,
    },
  },
  {
    id: 'water-collector',
    name: 'Swimmer',
    description: 'Collect 100 Water-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Water',
      targetCount: 100,
    },
  },
  {
    id: 'grass-collector',
    name: 'Aroma Lady',
    description: 'Collect 100 Grass-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Grass',
      targetCount: 100,
    },
  },
  {
    id: 'electric-collector',
    name: 'Rocker',
    description: 'Collect 100 Electric-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Electric',
      targetCount: 100,
    },
  },
  {
    id: 'psychic-collector',
    name: 'Psychic',
    description: 'Collect 100 Psychic-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Psychic',
      targetCount: 100,
    },
  },
  {
    id: 'ice-collector',
    name: 'Skier',
    description: 'Collect 100 Ice-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Ice',
      targetCount: 100,
    },
  },
  {
    id: 'dragon-collector',
    name: 'Dragon Tamer',
    description: 'Collect 100 Dragon-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Dragon',
      targetCount: 100,
    },
  },
  {
    id: 'dark-collector',
    name: 'Delinquent',
    description: 'Collect 100 Dark-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Dark',
      targetCount: 100,
    },
  },
  {
    id: 'fairy-collector',
    name: 'Fairy Tale Girl',
    description: 'Collect 100 Fairy-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Fairy',
      targetCount: 100,
    },
  },
   {
    id: 'stellar-collector',
    name: 'The 19th Type',
    description: 'Collect 5 Stellar-Type cards.',
    showIcons: false,
    collectionGoal: {
      property: 'type',
      value: 'Stellar',
      targetCount: 5,
    },
  },
  {
    id: 'shiny-hunter',
    name: 'Shiny Hunter',
    description: 'Collect 10 Shiny Pokémon cards.',
    showIcons: false,
    collectionGoal: {
      property: 'isShiny',
      targetCount: 10,
    },
  },
  {
    id: 'mythical-master',
    name: 'Mythical Master',
    description: 'Collect 10 Mythical Pokémon cards.',
    showIcons: false,
    collectionGoal: {
      property: 'rarity',
      value: 'Mythical',
      targetCount: 10,
    },
  },
//   {
//     id: 'kanto-collector',
//     name: 'Kanto Completionist',
//     description: 'Collect all Pokémon cards from the Kanto region.',
//     showIcons: false,
//     collectionGoal: {
//       property: 'region',
//       value: 'Kanto',
//       targetCount: 151
//     },
//   },
];