export interface Card {
  name: string;
  number: number;
  type: string[];
  rarity: 'Common' | 'Uncommon' | 'Rare' | 'Epic' | 'Legendary' | 'Mythical';
  move: string;
}

export const allCards: Card[] = [
    // Kanto
  { name: 'Bulbasaur', number: 1, type: ['Grass', 'Poison'], rarity: 'Uncommon', move: 'Vine Whip' },
  { name: 'Ivysaur', number: 2, type: ['Grass', 'Poison'], rarity: 'Rare', move: 'Razor Leaf' },
  { name: 'Venusaur', number: 3, type: ['Grass', 'Poison'], rarity: 'Epic', move: 'Solar Beam' },
  { name: 'Charmander', number: 4, type: ['Fire'], rarity: 'Uncommon', move: 'Ember' },
  { name: 'Charmeleon', number: 5, type: ['Fire'], rarity: 'Rare', move: 'Flamethrower' },
  { name: 'Charizard', number: 6, type: ['Fire', 'Flying'], rarity: 'Epic', move: 'Fire Blast' },
  { name: 'Squirtle', number: 7, type: ['Water'], rarity: 'Uncommon', move: 'Water Gun' },
  { name: 'Wartortle', number: 8, type: ['Water'], rarity: 'Rare', move: 'Water Pulse' },
  { name: 'Blastoise', number: 9, type: ['Water'], rarity: 'Epic', move: 'Hydro Pump' },
  { name: 'Caterpie', number: 10, type: ['Bug'], rarity: 'Common', move: 'Tackle' },
  { name: 'Metapod', number: 11, type: ['Bug'], rarity: 'Common', move: 'Harden' },
  { name: 'Butterfree', number: 12, type: ['Bug', 'Flying'], rarity: 'Rare', move: 'Gust' },
  { name: 'Weedle', number: 13, type: ['Bug', 'Poison'], rarity: 'Common', move: 'Poison Sting' },
  { name: 'Kakuna', number: 14, type: ['Bug', 'Poison'], rarity: 'Common', move: 'Harden' },
  { name: 'Beedrill', number: 15, type: ['Bug', 'Poison'], rarity: 'Rare', move: 'Twineedle' },
  { name: 'Pidgey', number: 16, type: ['Normal', 'Flying'], rarity: 'Common', move: 'Tackle' },
  { name: 'Pidgeotto', number: 17, type: ['Normal', 'Flying'], rarity: 'Uncommon', move: 'Wing Attack' },
  { name: 'Pidgeot', number: 18, type: ['Normal', 'Flying'], rarity: 'Rare', move: 'Hurricane' },
  { name: 'Rattata', number: 19, type: ['Normal'], rarity: 'Common', move: 'Bite' },
  { name: 'Raticate', number: 20, type: ['Normal'], rarity: 'Uncommon', move: 'Hyper Fang' },
  { name: 'Spearow', number: 21, type: ['Normal', 'Flying'], rarity: 'Common', move: 'Peck' },
  { name: 'Fearow', number: 22, type: ['Normal', 'Flying'], rarity: 'Uncommon', move: 'Drill Peck' },
  { name: 'Ekans', number: 23, type: ['Poison'], rarity: 'Common', move: 'Poison Sting' },
  { name: 'Arbok', number: 24, type: ['Poison'], rarity: 'Rare', move: 'Gunk Shot' },
  { name: 'Pikachu', number: 25, type: ['Electric'], rarity: 'Uncommon', move: 'Thunderbolt' },
  { name: 'Raichu', number: 26, type: ['Electric'], rarity: 'Rare', move: 'Thunder' },
  { name: 'Sandshrew', number: 27, type: ['Ground'], rarity: 'Common', move: 'Dig' },
  { name: 'Sandslash', number: 28, type: ['Ground'], rarity: 'Rare', move: 'Earthquake' },
  { name: 'Nidoran♀', number: 29, type: ['Poison'], rarity: 'Common', move: 'Poison Sting' },
  { name: 'Nidorina', number: 30, type: ['Poison'], rarity: 'Uncommon', move: 'Double Kick' },
  { name: 'Nidoqueen', number: 31, type: ['Poison', 'Ground'], rarity: 'Epic', move: 'Earth Power' },
  { name: 'Nidoran♂', number: 32, type: ['Poison'], rarity: 'Common', move: 'Poison Sting' },
  { name: 'Nidorino', number: 33, type: ['Poison'], rarity: 'Uncommon', move: 'Horn Attack' },
  { name: 'Nidoking', number: 34, type: ['Poison', 'Ground'], rarity: 'Epic', move: 'Megahorn' },
  { name: 'Clefairy', number: 35, type: ['Fairy'], rarity: 'Uncommon', move: 'Moonblast' },
  { name: 'Clefable', number: 36, type: ['Fairy'], rarity: 'Rare', move: 'Meteor Mash' },
  { name: 'Vulpix', number: 37, type: ['Fire'], rarity: 'Uncommon', move: 'Flamethrower' },
  { name: 'Ninetales', number: 38, type: ['Fire'], rarity: 'Rare', move: 'Fire Spin' },
  { name: 'Jigglypuff', number: 39, type: ['Normal', 'Fairy'], rarity: 'Common', move: 'Sing' },
  { name: 'Wigglytuff', number: 40, type: ['Normal', 'Fairy'], rarity: 'Rare', move: 'Hyper Voice' },
  { name: 'Zubat', number: 41, type: ['Poison', 'Flying'], rarity: 'Common', move: 'Leech Life' },
  { name: 'Golbat', number: 42, type: ['Poison', 'Flying'], rarity: 'Uncommon', move: 'Air Slash' },
  { name: 'Oddish', number: 43, type: ['Grass', 'Poison'], rarity: 'Common', move: 'Absorb' },
  { name: 'Gloom', number: 44, type: ['Grass', 'Poison'], rarity: 'Uncommon', move: 'Acid' },
  { name: 'Vileplume', number: 45, type: ['Grass', 'Poison'], rarity: 'Rare', move: 'Petal Dance' },
  { name: 'Paras', number: 46, type: ['Bug', 'Grass'], rarity: 'Common', move: 'Spore' },
  { name: 'Parasect', number: 47, type: ['Bug', 'Grass'], rarity: 'Uncommon', move: 'X-Scissor' },
  { name: 'Venonat', number: 48, type: ['Bug', 'Poison'], rarity: 'Common', move: 'Bug Bite' },
  { name: 'Venomoth', number: 49, type: ['Bug', 'Poison'], rarity: 'Rare', move: 'Psybeam' },
  { name: 'Diglett', number: 50, type: ['Ground'], rarity: 'Common', move: 'Dig' },
  { name: 'Dugtrio', number: 51, type: ['Ground'], rarity: 'Rare', move: 'Earthquake' },
  { name: 'Meowth', number: 52, type: ['Normal'], rarity: 'Common', move: 'Scratch' },
  { name: 'Persian', number: 53, type: ['Normal'], rarity: 'Rare', move: 'Slash' },
  { name: 'Psyduck', number: 54, type: ['Water'], rarity: 'Common', move: 'Water Gun' },
  { name: 'Golduck', number: 55, type: ['Water'], rarity: 'Rare', move: 'Hydro Pump' },
  { name: 'Mankey', number: 56, type: ['Fighting'], rarity: 'Common', move: 'Karate Chop' },
  { name: 'Primeape', number: 57, type: ['Fighting'], rarity: 'Rare', move: 'Cross Chop' },
  { name: 'Growlithe', number: 58, type: ['Fire'], rarity: 'Uncommon', move: 'Flame Wheel' },
  { name: 'Arcanine', number: 59, type: ['Fire'], rarity: 'Epic', move: 'Flare Blitz' },
  { name: 'Poliwag', number: 60, type: ['Water'], rarity: 'Common', move: 'Bubble' },
  { name: 'Poliwhirl', number: 61, type: ['Water'], rarity: 'Uncommon', move: 'Bubble Beam' },
  { name: 'Poliwrath', number: 62, type: ['Water', 'Fighting'], rarity: 'Epic', move: 'Dynamic Punch' },
  { name: 'Abra', number: 63, type: ['Psychic'], rarity: 'Uncommon', move: 'Teleport' },
  { name: 'Kadabra', number: 64, type: ['Psychic'], rarity: 'Rare', move: 'Psybeam' },
  { name: 'Alakazam', number: 65, type: ['Psychic'], rarity: 'Epic', move: 'Psychic' },
  { name: 'Machop', number: 66, type: ['Fighting'], rarity: 'Common', move: 'Low Kick' },
  { name: 'Machoke', number: 67, type: ['Fighting'], rarity: 'Uncommon', move: 'Karate Chop' },
  { name: 'Machamp', number: 68, type: ['Fighting'], rarity: 'Epic', move: 'Dynamic Punch' },
  { name: 'Bellsprout', number: 69, type: ['Grass', 'Poison'], rarity: 'Common', move: 'Vine Whip' },
  { name: 'Weepinbell', number: 70, type: ['Grass', 'Poison'], rarity: 'Uncommon', move: 'Razor Leaf' },
  { name: 'Victreebel', number: 71, type: ['Grass', 'Poison'], rarity: 'Rare', move: 'Leaf Blade' },
  { name: 'Tentacool', number: 72, type: ['Water', 'Poison'], rarity: 'Common', move: 'Poison Sting' },
  { name: 'Tentacruel', number: 73, type: ['Water', 'Poison'], rarity: 'Rare', move: 'Hydro Pump' },
  { name: 'Geodude', number: 74, type: ['Rock', 'Ground'], rarity: 'Common', move: 'Rock Throw' },
  { name: 'Graveler', number: 75, type: ['Rock', 'Ground'], rarity: 'Uncommon', move: 'Rollout' },
  { name: 'Golem', number: 76, type: ['Rock', 'Ground'], rarity: 'Epic', move: 'Stone Edge' },
  { name: 'Ponyta', number: 77, type: ['Fire'], rarity: 'Uncommon', move: 'Flame Wheel' },
  { name: 'Rapidash', number: 78, type: ['Fire'], rarity: 'Rare', move: 'Flare Blitz' },
  { name: 'Slowpoke', number: 79, type: ['Water', 'Psychic'], rarity: 'Common', move: 'Water Gun' },
  { name: 'Slowbro', number: 80, type: ['Water', 'Psychic'], rarity: 'Rare', move: 'Psychic' },
  { name: 'Magnemite', number: 81, type: ['Electric', 'Steel'], rarity: 'Common', move: 'Thunder Shock' },
  { name: 'Magneton', number: 82, type: ['Electric', 'Steel'], rarity: 'Rare', move: 'Discharge' },
  { name: 'Farfetch\'d', number: 83, type: ['Normal', 'Flying'], rarity: 'Uncommon', move: 'Aerial Ace' },
  { name: 'Doduo', number: 84, type: ['Normal', 'Flying'], rarity: 'Common', move: 'Peck' },
  { name: 'Dodrio', number: 85, type: ['Normal', 'Flying'], rarity: 'Rare', move: 'Drill Peck' },
  { name: 'Seel', number: 86, type: ['Water'], rarity: 'Common', move: 'Aqua Jet' },
  { name: 'Dewgong', number: 87, type: ['Water', 'Ice'], rarity: 'Rare', move: 'Ice Beam' },
  { name: 'Grimer', number: 88, type: ['Poison'], rarity: 'Common', move: 'Sludge' },
  { name: 'Muk', number: 89, type: ['Poison'], rarity: 'Rare', move: 'Sludge Bomb' },
  { name: 'Shellder', number: 90, type: ['Water'], rarity: 'Common', move: 'Tackle' },
  { name: 'Cloyster', number: 91, type: ['Water', 'Ice'], rarity: 'Rare', move: 'Icicle Spear' },
  { name: 'Gastly', number: 92, type: ['Ghost', 'Poison'], rarity: 'Uncommon', move: 'Lick' },
  { name: 'Haunter', number: 93, type: ['Ghost', 'Poison'], rarity: 'Rare', move: 'Shadow Ball' },
  { name: 'Gengar', number: 94, type: ['Ghost', 'Poison'], rarity: 'Epic', move: 'Destiny Bond' },
  { name: 'Onix', number: 95, type: ['Rock', 'Ground'], rarity: 'Uncommon', move: 'Rock Slide' },
  { name: 'Drowzee', number: 96, type: ['Psychic'], rarity: 'Common', move: 'Hypnosis' },
  { name: 'Hypno', number: 97, type: ['Psychic'], rarity: 'Rare', move: 'Dream Eater' },
  { name: 'Krabby', number: 98, type: ['Water'], rarity: 'Common', move: 'Bubble' },
  { name: 'Kingler', number: 99, type: ['Water'], rarity: 'Rare', move: 'Crabhammer' },
  { name: 'Voltorb', number: 100, type: ['Electric'], rarity: 'Common', move: 'Spark' },
  { name: 'Electrode', number: 101, type: ['Electric'], rarity: 'Rare', move: 'Thunderbolt' },
  { name: 'Exeggcute', number: 102, type: ['Grass', 'Psychic'], rarity: 'Common', move: 'Bullet Seed' },
  { name: 'Exeggutor', number: 103, type: ['Grass', 'Psychic'], rarity: 'Epic', move: 'Solar Beam' },
  { name: 'Cubone', number: 104, type: ['Ground'], rarity: 'Uncommon', move: 'Bone Club' },
  { name: 'Marowak', number: 105, type: ['Ground'], rarity: 'Rare', move: 'Bonemerang' },
  { name: 'Hitmonlee', number: 106, type: ['Fighting'], rarity: 'Rare', move: 'High Jump Kick' },
  { name: 'Hitmonchan', number: 107, type: ['Fighting'], rarity: 'Rare', move: 'Mach Punch' },
  { name: 'Lickitung', number: 108, type: ['Normal'], rarity: 'Uncommon', move: 'Lick' },
  { name: 'Koffing', number: 109, type: ['Poison'], rarity: 'Common', move: 'Smog' },
  { name: 'Weezing', number: 110, type: ['Poison'], rarity: 'Rare', move: 'Sludge Bomb' },
  { name: 'Rhyhorn', number: 111, type: ['Ground', 'Rock'], rarity: 'Uncommon', move: 'Rock Blast' },
  { name: 'Rhydon', number: 112, type: ['Ground', 'Rock'], rarity: 'Epic', move: 'Stone Edge' },
  { name: 'Chansey', number: 113, type: ['Normal'], rarity: 'Rare', move: 'Soft-Boiled' },
  { name: 'Tangela', number: 114, type: ['Grass'], rarity: 'Uncommon', move: 'Vine Whip' },
  { name: 'Kangaskhan', number: 115, type: ['Normal'], rarity: 'Rare', move: 'Mega Punch' },
  { name: 'Horsea', number: 116, type: ['Water'], rarity: 'Common', move: 'Bubble' },
  { name: 'Seadra', number: 117, type: ['Water'], rarity: 'Rare', move: 'Hydro Pump' },
  { name: 'Goldeen', number: 118, type: ['Water'], rarity: 'Common', move: 'Water Pulse' },
  { name: 'Seaking', number: 119, type: ['Water'], rarity: 'Uncommon', move: 'Waterfall' },
  { name: 'Staryu', number: 120, type: ['Water'], rarity: 'Common', move: 'Water Gun' },
  { name: 'Starmie', number: 121, type: ['Water', 'Psychic'], rarity: 'Rare', move: 'Psychic' },
  { name: 'Mr. Mime', number: 122, type: ['Psychic', 'Fairy'], rarity: 'Rare', move: 'Barrier' },
  { name: 'Scyther', number: 123, type: ['Bug', 'Flying'], rarity: 'Rare', move: 'X-Scissor' },
  { name: 'Jynx', number: 124, type: ['Ice', 'Psychic'], rarity: 'Rare', move: 'Ice Beam' },
  { name: 'Electabuzz', number: 125, type: ['Electric'], rarity: 'Rare', move: 'Thunder Punch' },
  { name: 'Magmar', number: 126, type: ['Fire'], rarity: 'Rare', move: 'Fire Punch' },
  { name: 'Pinsir', number: 127, type: ['Bug'], rarity: 'Rare', move: 'Vice Grip' },
  { name: 'Tauros', number: 128, type: ['Normal'], rarity: 'Rare', move: 'Take Down' },
  { name: 'Magikarp', number: 129, type: ['Water'], rarity: 'Common', move: 'Splash' },
  { name: 'Gyarados', number: 130, type: ['Water', 'Flying'], rarity: 'Epic', move: 'Hydro Pump' },
  { name: 'Lapras', number: 131, type: ['Water', 'Ice'], rarity: 'Rare', move: 'Ice Beam' },
  { name: 'Ditto', number: 132, type: ['Normal'], rarity: 'Uncommon', move: 'Transform' },
  { name: 'Eevee', number: 133, type: ['Normal'], rarity: 'Uncommon', move: 'Tackle' },
  { name: 'Vaporeon', number: 134, type: ['Water'], rarity: 'Rare', move: 'Hydro Pump' },
  { name: 'Jolteon', number: 135, type: ['Electric'], rarity: 'Rare', move: 'Thunderbolt' },
  { name: 'Flareon', number: 136, type: ['Fire'], rarity: 'Rare', move: 'Flamethrower' },
  { name: 'Porygon', number: 137, type: ['Normal'], rarity: 'Uncommon', move: 'Tri Attack' },
  { name: 'Omanyte', number: 138, type: ['Rock', 'Water'], rarity: 'Uncommon', move: 'Water Gun' },
  { name: 'Omastar', number: 139, type: ['Rock', 'Water'], rarity: 'Rare', move: 'Hydro Pump' },
  { name: 'Kabuto', number: 140, type: ['Rock', 'Water'], rarity: 'Uncommon', move: 'Rock Throw' },
  { name: 'Kabutops', number: 141, type: ['Rock', 'Water'], rarity: 'Rare', move: 'Stone Edge' },
  { name: 'Aerodactyl', number: 142, type: ['Rock', 'Flying'], rarity: 'Epic', move: 'Hyper Beam' },
  { name: 'Snorlax', number: 143, type: ['Normal'], rarity: 'Epic', move: 'Body Slam' },
  { name: 'Articuno', number: 144, type: ['Ice', 'Flying'], rarity: 'Legendary', move: 'Blizzard' },
  { name: 'Zapdos', number: 145, type: ['Electric', 'Flying'], rarity: 'Legendary', move: 'Thunder' },
  { name: 'Moltres', number: 146, type: ['Fire', 'Flying'], rarity: 'Legendary', move: 'Flamethrower' },
  { name: 'Dratini', number: 147, type: ['Dragon'], rarity: 'Uncommon', move: 'Dragon Tail' },
  { name: 'Dragonair', number: 148, type: ['Dragon'], rarity: 'Rare', move: 'Dragon Pulse' },
  { name: 'Dragonite', number: 149, type: ['Dragon', 'Flying'], rarity: 'Epic', move: 'Draco Meteor' },
  { name: 'Mewtwo', number: 150, type: ['Psychic'], rarity: 'Legendary', move: 'Psystrike' },
  { name: 'Mew', number: 151, type: ['Psychic'], rarity: 'Mythical', move: 'Psychic' },

  // Johto
  { name: 'Chikorita', number: 152, type: ['Grass'], rarity: 'Uncommon', move: 'Razor Leaf'},
  { name: 'Bayleef', number: 153, type: ['Grass'], rarity: 'Rare', move: 'Magical Leaf'},
  { name: 'Meganium', number: 154, type: ['Grass'], rarity: 'Epic', move: 'Petal Blizzard'},
  { name: 'Cyndaquil', number: 155, type: ['Fire'], rarity: 'Uncommon', move: 'Ember'},
  { name: 'Quilava', number: 156, type: ['Fire'], rarity: 'Rare', move: 'Flame Wheel'},
  { name: 'Typhlosion', number: 157, type: ['Fire'], rarity: 'Epic', move: 'Eruption'},
  { name: 'Totodile', number: 158, type: ['Water'], rarity: 'Uncommon', move: 'Water Gun'},
  { name: 'Croconaw', number: 159, type: ['Water'], rarity: 'Rare', move: 'Aqua Tail'},
  { name: 'Feraligatr', number: 160, type: ['Water'], rarity: 'Epic', move: 'Hydro Pump'},
  { name: 'Sentret', number: 161, type: ['Normal'], rarity: 'Common', move: 'Tackle'},
  { name: 'Furret', number: 162, type: ['Normal'], rarity: 'Uncommon', move: 'Hyper Voice'},
  { name: 'Hoothoot', number: 163, type: ['Normal', 'Flying'], rarity: 'Common', move: 'Peck'},
  { name: 'Noctowl', number: 164, type: ['Normal', 'Flying'], rarity: 'Rare', move: 'Air Slash'},
  { name: 'Ledyba', number: 165, type: ['Bug', 'Flying'], rarity: 'Common', move: 'Bug Bite'},
  { name: 'Ledian', number: 166, type: ['Bug', 'Flying'], rarity: 'Uncommon', move: 'Silver Wind'},
  { name: 'Spinarak', number: 167, type: ['Bug', 'Poison'], rarity: 'Common', move: 'Poison Sting'},
  { name: 'Ariados', number: 168, type: ['Bug', 'Poison'], rarity: 'Uncommon', move: 'Cross Poison'},
  { name: 'Crobat', number: 169, type: ['Poison', 'Flying'], rarity: 'Rare', move: 'Air Cutter'},
  { name: 'Chinchou', number: 170, type: ['Water', 'Electric'], rarity: 'Uncommon', move: 'Spark'},
  { name: 'Lanturn', number: 171, type: ['Water', 'Electric'], rarity: 'Rare', move: 'Discharge'},
  { name: 'Pichu', number: 172, type: ['Electric'], rarity: 'Common', move: 'Thunder Shock'},
  { name: 'Cleffa', number: 173, type: ['Fairy'], rarity: 'Common', move: 'Pound'},
  { name: 'Igglybuff', number: 174, type: ['Normal, Fairy'], rarity: 'Common', move: 'Sing'},
  { name: 'Togepi', number: 175, type: ['Fairy'], rarity: 'Uncommon', move: 'Metronome'},
  { name: 'Togetic', number: 176, type: ['Fairy', 'Flying'], rarity: 'Rare', move: 'Fairy Wind'},
  { name: 'Natu', number: 177, type: ['Psychic', 'Flying'], rarity: 'Common', move: 'Peck'},
  { name: 'Xatu', number: 178, type: ['Psychic', 'Flying'], rarity: 'Rare', move: 'Future Sight'},
  { name: 'Mareep', number: 179, type: ['Electric'], rarity: 'Common', move: 'Thunder Shock'},
  { name: 'Flaaffy', number: 180, type: ['Electric'], rarity: 'Uncommon', move: 'Thunderbolt'},
  { name: 'Ampharos', number: 181, type: ['Electric'], rarity: 'Rare', move: 'Thunder'},
  { name: 'Bellossom', number: 182, type: ['Grass'], rarity: 'Rare', move: 'Petal Dance'},
  { name: 'Marill', number: 183, type: ['Water, Fairy'], rarity: 'Uncommon', move: 'Bubble'},
  { name: 'Azumarill', number: 184, type: ['Water, Fairy'], rarity: 'Rare', move: 'Aqua Tail'},
  { name: 'Sudowoodo', number: 185, type: ['Rock'], rarity: 'Uncommon', move: 'Rock Throw'},
  { name: 'Politoed', number: 186, type: ['Water'], rarity: 'Rare', move: 'Hydro Pump'},
  { name: 'Hoppip', number: 187, type: ['Grass', 'Flying'], rarity: 'Common', move: 'Tackle'},
  { name: 'Skiploom', number: 188, type: ['Grass', 'Flying'], rarity: 'Uncommon', move: 'Bullet Seed'},
  { name: 'Jumpluff', number: 189, type: ['Grass', 'Flying'], rarity: 'Rare', move: 'Aerial Ace'},
  { name: 'Aipom', number: 190, type: ['Normal'], rarity: 'Uncommon', move: 'Scratch'},
  { name: 'Sunkern', number: 191, type: ['Grass'], rarity: 'Common', move: 'Absorb'},
  { name: 'Sunflora', number: 192, type: ['Grass'], rarity: 'Uncommon', move: 'Solar Beam'},
  { name: 'Yanma', number: 193, type: ['Bug', 'Flying'], rarity: 'Uncommon', move: 'Wing Attack'},
  { name: 'Wooper', number: 194, type: ['Water', 'Ground'], rarity: 'Common', move: 'Mud Shot'},
  { name: 'Quagsire', number: 195, type: ['Water', 'Ground'], rarity: 'Rare', move: 'Earthquake'},
  { name: 'Espeon', number: 196, type: ['Psychic'], rarity: 'Rare', move: 'Psychic'},
  { name: 'Umbreon', number: 197, type: ['Dark'], rarity: 'Rare', move: 'Dark Pulse'},
  { name: 'Murkrow', number: 198, type: ['Dark', 'Flying'], rarity: 'Uncommon', move: 'Peck'},
  { name: 'Slowking', number: 199, type: ['Water', 'Psychic'], rarity: 'Rare', move: 'Confusion'},
  { name: 'Misdreavus', number: 200, type: ['Ghost'], rarity: 'Uncommon', move: 'Shadow Ball'},
  { name: 'Unown', number: 201, type: ['Psychic'], rarity: 'Uncommon', move: 'Hidden Power'},
  { name: 'Wobbuffet', number: 202, type: ['Psychic'], rarity: 'Uncommon', move: 'Counter'},
  { name: 'Girafarig', number: 203, type: ['Normal', 'Psychic'], rarity: 'Uncommon', move: 'Psybeam'},
  { name: 'Pineco', number: 204, type: ['Bug'], rarity: 'Common', move: 'Tackle'},
  { name: 'Forretress', number: 205, type: ['Bug', 'Steel'], rarity: 'Rare', move: 'Explosion'},
  { name: 'Dunsparce', number: 206, type: ['Normal'], rarity: 'Uncommon', move: 'Rollout'},
  { name: 'Gligar', number: 207, type: ['Ground', 'Flying'], rarity: 'Uncommon', move: 'Slash'},
  { name: 'Steelix', number: 208, type: ['Steel', 'Ground'], rarity: 'Rare', move: 'Iron Tail'},
  { name: 'Snubbull', number: 209, type: ['Fairy'], rarity: 'Common', move: 'Bite'},
  { name: 'Granbull', number: 210, type: ['Fairy'], rarity: 'Rare', move: 'Play Rough'},
  { name: 'Qwilfish', number: 211, type: ['Water', 'Poison'], rarity: 'Uncommon', move: 'Poison Sting'},
  { name: 'Scizor', number: 212, type: ['Bug', 'Steel'], rarity: 'Rare', move: 'Bullet Punch'},
  { name: 'Shuckle', number: 213, type: ['Bug', 'Rock'], rarity: 'Uncommon', move: 'Rock Throw'},
  { name: 'Heracross', number: 214, type: ['Bug', 'Fighting'], rarity: 'Rare', move: 'Megahorn'},
  { name: 'Sneasel', number: 215, type: ['Dark', 'Ice'], rarity: 'Uncommon', move: 'Ice Shard'},
  { name: 'Teddiursa', number: 216, type: ['Normal'], rarity: 'Common', move: 'Scratch'},
  { name: 'Ursaring', number: 217, type: ['Normal'], rarity: 'Rare', move: 'Hyper Beam'},
  { name: 'Slugma', number: 218, type: ['Fire'], rarity: 'Common', move: 'Ember'},
  { name: 'Magcargo', number: 219, type: ['Fire', 'Rock'], rarity: 'Rare', move: 'Flamethrower'},
  { name: 'Swinub', number: 220, type: ['Ice', 'Ground'], rarity: 'Common', move: 'Powder Snow'},
  { name: 'Piloswine', number: 221, type: ['Ice', 'Ground'], rarity: 'Rare', move: 'Blizzard'},
  { name: 'Corsola', number: 222, type: ['Water', 'Rock'], rarity: 'Uncommon', move: 'Bubble Beam'},
  { name: 'Remoraid', number: 223, type: ['Water'], rarity: 'Common', move: 'Water Gun'},
  { name: 'Octillery', number: 224, type: ['Water'], rarity: 'Rare', move: 'Octazooka'},
  { name: 'Delibird', number: 225, type: ['Ice', 'Flying'], rarity: 'Uncommon', move: 'Present'},
  { name: 'Mantine', number: 226, type: ['Water', 'Flying'], rarity: 'Rare', move: 'Wing Attack'},
  { name: 'Skarmory', number: 227, type: ['Steel', 'Flying'], rarity: 'Rare', move: 'Steel Wing'},
  { name: 'Houndour', number: 228, type: ['Dark', 'Fire'], rarity: 'Uncommon', move: 'Ember'},
  { name: 'Houndoom', number: 229, type: ['Dark', 'Fire'], rarity: 'Rare', move: 'Flamethrower'},
  { name: 'Kingdra', number: 230, type: ['Water', 'Dragon'], rarity: 'Rare', move: 'Dragon Pulse'},
  { name: 'Phanpy', number: 231, type: ['Ground'], rarity: 'Common', move: 'Tackle'},
  { name: 'Donphan', number: 232, type: ['Ground'], rarity: 'Rare', move: 'Earthquake'},
  { name: 'Porygon2', number: 233, type: ['Normal'], rarity: 'Rare', move: 'Zap Cannon'},
  { name: 'Stantler', number: 234, type: ['Normal'], rarity: 'Uncommon', move: 'Stomp'},
  { name: 'Smeargle', number: 235, type: ['Normal'], rarity: 'Uncommon', move: 'Sketch'},
  { name: 'Tyrogue', number: 236, type: ['Fighting'], rarity: 'Common', move: 'Tackle'},
  { name: 'Hitmontop', number: 237, type: ['Fighting'], rarity: 'Rare', move: 'Triple Kick'},
  { name: 'Smoochum', number: 238, type: ['Ice', 'Psychic'], rarity: 'Common', move: 'Powder Snow'},
  { name: 'Elekid', number: 239, type: ['Electric'], rarity: 'Common', move: 'Thunder Punch'},
  { name: 'Magby', number: 240, type: ['Fire'], rarity: 'Common', move: 'Fire Punch'},
  { name: 'Miltank', number: 241, type: ['Normal'], rarity: 'Rare', move: 'Rollout'},
  { name: 'Blissey', number: 242, type: ['Normal'], rarity: 'Rare', move: 'Soft-Boiled'},
  { name: 'Raikou', number: 243, type: ['Electric'], rarity: 'Legendary', move: 'Thunder'},
  { name: 'Entei', number: 244, type: ['Fire'], rarity: 'Legendary', move: 'Sacred Fire'},
  { name: 'Suicune', number: 245, type: ['Water'], rarity: 'Legendary', move: 'Aurora Beam'},
  { name: 'Larvitar', number: 246, type: ['Rock', 'Ground'], rarity: 'Uncommon', move: 'Rock Throw'},
  { name: 'Pupitar', number: 247, type: ['Rock', 'Ground'], rarity: 'Rare', move: 'Rock Slide'},
  { name: 'Tyranitar', number: 248, type: ['Rock', 'Dark'], rarity: 'Epic', move: 'Crunch'},
  { name: 'Lugia', number: 249, type: ['Psychic', 'Flying'], rarity: 'Legendary', move: 'Aeroblast'},
  { name: 'Ho-Oh', number: 250, type: ['Fire', 'Flying'], rarity: 'Legendary', move: 'Sacred Fire'},
  { name: 'Celebi', number: 251, type: ['Psychic', 'Grass'], rarity: 'Mythical', move: 'Magical Leaf'},
];